[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_summer_t22 = "FkaFBQKxZWYCzGqSC3xsUggiT8E9Swsopsu2gQJH3pi"
transfer_hook = "Dszak9xWCHKeMKbNWx27u4mpo5ADFwqmC4iBS2w3bccZ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
